SSH_HOST = "staff.oamk.fi"
SSH_USER = "villemaj"
SSH_PASSWORD = "M3r1h3lm1D4n13l"  # Vaihda salasanaan tai käytä ssh-avainta
MYSQL_HOST = "mysli.oamk.fi"
MYSQL_USER = "villemaj"
MYSQL_PASSWORD = "hZUELZdD8Zg5pWTx"
MYSQL_DATABASE = "opisk_villemaj"
